### ISSUE TITLE
currently equipped

### ISSUE THREAD

**Issue by Imna1975** [Marsgames/GearHelper#79]
currently equipped can it be that the values are no longer current?

![wow  vergleich _LI](https://user-images.githubusercontent.com/45740014/75179219-e0884200-5739-11ea-8372-1f318fd73d12.jpg)

**Comment by Marsgames** [comment]
Hey,

The fact is that the Blizzard's function we use considers that this two items are the same, because it's the same item link, and it's just the stats that are differents.

We could write our own function to check if items are the same or not, but in most cases (maybe more than 90% of the time, when you don't test the same item with a better ilvl) our own function would be slower than Blizzard's one.

So atm it's more interesting to keep this error but have a faster result 90% of the time.

**Comment by Imna1975** [comment]
thanks again for the info
